/**
 * PDF Report Generator
 * ====================
 *
 * Generates a downloadable PDF accessibility report from analysis results.
 * Uses jsPDF for direct PDF construction (no HTML-to-PDF conversion).
 *
 * Report sections:
 *   1. Cover — title, date, floor plan name, score
 *   2. Summary — severity breakdown
 *   3. Issues — grouped by category with ADA references
 *   4. AI Insights — Gemini recommendations (if available)
 */

import { jsPDF } from 'jspdf';
import type { AnalysisResult, Issue, RuleCategory } from '../types';

// ─── Constants ──────────────────────────────────────────────────────

const COLORS = {
    bg: '#0f172a',
    text: '#e2e8f0',
    textMuted: '#94a3b8',
    primary: '#3b82f6',
    critical: '#ef4444',
    warning: '#eab308',
    info: '#3b82f6',
    green: '#22c55e',
    divider: '#334155',
} as const;

const CATEGORY_LABELS: Record<RuleCategory, string> = {
    doorways: 'Doorways',
    pathways: 'Pathways',
    ramps: 'Ramps & Elevators',
    counters: 'Counters & Surfaces',
    bathroom: 'Bathroom',
    elevators: 'Elevators',
    exits: 'Exits',
    furniture: 'Furniture',
};

const SEVERITY_LABELS: Record<string, string> = {
    critical: 'CRITICAL',
    warning: 'WARNING',
    info: 'INFO',
};

const PAGE_WIDTH = 210;   // A4 mm
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

// ─── Helpers ────────────────────────────────────────────────────────

function hexToRGB(hex: string): [number, number, number] {
    const h = hex.replace('#', '');
    return [
        parseInt(h.substring(0, 2), 16),
        parseInt(h.substring(2, 4), 16),
        parseInt(h.substring(4, 6), 16),
    ];
}

/** Ensure we have space; add a page if not */
function ensureSpace(doc: jsPDF, y: number, needed: number): number {
    if (y + needed > PAGE_HEIGHT - MARGIN) {
        doc.addPage();
        return MARGIN + 10;
    }
    return y;
}

/** Draw page footer */
function drawFooter(doc: jsPDF, pageNum: number) {
    doc.setFontSize(8);
    doc.setTextColor(...hexToRGB(COLORS.textMuted));
    doc.text(`Page ${pageNum}`, PAGE_WIDTH / 2, PAGE_HEIGHT - 10, { align: 'center' });
    doc.text('Generated by Ben10 Accessibility Checker', PAGE_WIDTH / 2, PAGE_HEIGHT - 6, { align: 'center' });
}

// ─── Score Color ────────────────────────────────────────────────────

function getScoreColor(score: number): string {
    if (score >= 80) return COLORS.green;
    if (score >= 50) return COLORS.warning;
    return COLORS.critical;
}

// ─── Main Export Function ───────────────────────────────────────────

export function generateAccessibilityReport(
    result: AnalysisResult,
    floorPlanName: string,
): void {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    let pageNum = 1;

    // ════════════════════════════════════════════════════════════════
    // PAGE 1 — COVER & SUMMARY
    // ════════════════════════════════════════════════════════════════

    // Background
    doc.setFillColor(...hexToRGB(COLORS.bg));
    doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

    // Title
    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...hexToRGB(COLORS.text));
    doc.text('Accessibility Analysis', PAGE_WIDTH / 2, 40, { align: 'center' });
    doc.text('Report', PAGE_WIDTH / 2, 52, { align: 'center' });

    // Subtitle — floor plan name
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...hexToRGB(COLORS.primary));
    doc.text(floorPlanName || 'Untitled Floor Plan', PAGE_WIDTH / 2, 66, { align: 'center' });

    // Date
    doc.setFontSize(10);
    doc.setTextColor(...hexToRGB(COLORS.textMuted));
    const dateStr = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit',
    });
    doc.text(dateStr, PAGE_WIDTH / 2, 76, { align: 'center' });

    // ── Score circle ──
    const scoreCenterX = PAGE_WIDTH / 2;
    const scoreCenterY = 110;
    const scoreRadius = 22;

    // Outer ring
    doc.setDrawColor(...hexToRGB(getScoreColor(result.score)));
    doc.setLineWidth(2);
    doc.circle(scoreCenterX, scoreCenterY, scoreRadius, 'S');

    // Inner ring (track)
    doc.setDrawColor(...hexToRGB(COLORS.divider));
    doc.setLineWidth(0.5);
    doc.circle(scoreCenterX, scoreCenterY, scoreRadius - 3, 'S');

    // Score number
    doc.setFontSize(36);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...hexToRGB(getScoreColor(result.score)));
    doc.text(String(result.score), scoreCenterX, scoreCenterY + 5, { align: 'center' });

    // Score label
    doc.setFontSize(10);
    doc.setTextColor(...hexToRGB(COLORS.textMuted));
    doc.text('Accessibility Score', scoreCenterX, scoreCenterY + scoreRadius + 10, { align: 'center' });

    // Score verdict
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    const verdict = result.score >= 80 ? 'COMPLIANT' : result.score >= 50 ? 'NEEDS IMPROVEMENT' : 'NON-COMPLIANT';
    doc.setTextColor(...hexToRGB(getScoreColor(result.score)));
    doc.text(verdict, scoreCenterX, scoreCenterY + scoreRadius + 18, { align: 'center' });

    // ── Severity summary boxes ──
    const criticals = result.issues.filter((i) => i.severity === 'critical').length;
    const warnings = result.issues.filter((i) => i.severity === 'warning').length;
    const infos = result.issues.filter((i) => i.severity === 'info').length;

    const boxY = 165;
    const boxW = 50;
    const boxH = 28;
    const gap = 10;
    const startX = (PAGE_WIDTH - 3 * boxW - 2 * gap) / 2;

    const severityBoxes = [
        { label: 'Critical', count: criticals, color: COLORS.critical },
        { label: 'Warnings', count: warnings, color: COLORS.warning },
        { label: 'Info', count: infos, color: COLORS.info },
    ];

    for (let i = 0; i < severityBoxes.length; i++) {
        const bx = startX + i * (boxW + gap);
        const { label, count, color } = severityBoxes[i];

        // Box background
        doc.setFillColor(...hexToRGB(COLORS.divider));
        doc.roundedRect(bx, boxY, boxW, boxH, 3, 3, 'F');

        // Top accent line
        doc.setFillColor(...hexToRGB(color));
        doc.rect(bx, boxY, boxW, 2, 'F');

        // Count
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...hexToRGB(color));
        doc.text(String(count), bx + boxW / 2, boxY + 14, { align: 'center' });

        // Label
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...hexToRGB(COLORS.textMuted));
        doc.text(label, bx + boxW / 2, boxY + 22, { align: 'center' });
    }

    // ── Stats row ──
    const statsY = 210;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...hexToRGB(COLORS.textMuted));
    doc.text(`Total Issues: ${result.issues.length}`, MARGIN, statsY);

    const categories = new Set(result.issues.map((i) => i.category));
    doc.text(`Categories Affected: ${categories.size} of ${Object.keys(CATEGORY_LABELS).length}`, MARGIN, statsY + 7);

    drawFooter(doc, pageNum);

    // ════════════════════════════════════════════════════════════════
    // PAGE 2+ — ISSUES BY CATEGORY
    // ════════════════════════════════════════════════════════════════

    doc.addPage();
    pageNum++;

    // Background
    doc.setFillColor(...hexToRGB(COLORS.bg));
    doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

    // Section title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...hexToRGB(COLORS.text));
    doc.text('Issues Breakdown', MARGIN, MARGIN + 8);

    // Divider
    doc.setDrawColor(...hexToRGB(COLORS.primary));
    doc.setLineWidth(0.5);
    doc.line(MARGIN, MARGIN + 12, PAGE_WIDTH - MARGIN, MARGIN + 12);

    let y = MARGIN + 20;

    // Group issues by category
    const issuesByCategory = new Map<RuleCategory, Issue[]>();
    for (const issue of result.issues) {
        const arr = issuesByCategory.get(issue.category) ?? [];
        arr.push(issue);
        issuesByCategory.set(issue.category, arr);
    }

    for (const [category, issues] of issuesByCategory) {
        // Check if we need a new page for the category header + at least 1 issue
        y = ensureSpace(doc, y, 30);
        if (y <= MARGIN + 15) {
            // New page — draw background
            doc.setFillColor(...hexToRGB(COLORS.bg));
            doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');
        }

        // Category header
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...hexToRGB(COLORS.primary));
        doc.text(`${CATEGORY_LABELS[category] ?? category}  (${issues.length})`, MARGIN, y);
        y += 3;

        // Thin line under category
        doc.setDrawColor(...hexToRGB(COLORS.divider));
        doc.setLineWidth(0.3);
        doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
        y += 5;

        for (const issue of issues) {
            // Estimate how much space this issue needs
            const descLines = doc.splitTextToSize(issue.description, CONTENT_WIDTH - 15);
            const issueHeight = 18 + descLines.length * 4;
            y = ensureSpace(doc, y, issueHeight);
            if (y <= MARGIN + 15) {
                doc.setFillColor(...hexToRGB(COLORS.bg));
                doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');
            }

            // Severity badge
            const sevColor = issue.severity === 'critical' ? COLORS.critical
                : issue.severity === 'warning' ? COLORS.warning : COLORS.info;
            doc.setFillColor(...hexToRGB(sevColor));
            const badgeText = SEVERITY_LABELS[issue.severity] ?? issue.severity.toUpperCase();
            const badgeW = doc.getTextWidth(badgeText) * 0.35 + 6;
            doc.roundedRect(MARGIN, y - 3, badgeW, 5, 1, 1, 'F');
            doc.setFontSize(7);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(255, 255, 255);
            doc.text(badgeText, MARGIN + 2, y);

            // Issue title
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...hexToRGB(COLORS.text));
            doc.text(issue.title, MARGIN + badgeW + 3, y);
            y += 5;

            // Description
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...hexToRGB(COLORS.textMuted));
            for (const line of descLines) {
                doc.text(line, MARGIN + 5, y);
                y += 4;
            }

            // ADA Standard reference
            if (issue.standard) {
                doc.setFontSize(7);
                doc.setFont('helvetica', 'italic');
                doc.setTextColor(...hexToRGB(COLORS.primary));
                doc.text(`📋 ${issue.standard}`, MARGIN + 5, y);
                y += 5;
            }

            y += 3; // gap between issues
        }

        y += 5; // gap between categories
    }

    drawFooter(doc, pageNum);

    // ════════════════════════════════════════════════════════════════
    // FINAL PAGE — AI INSIGHTS (if available)
    // ════════════════════════════════════════════════════════════════

    if (result.geminiInsights && result.geminiInsights.trim().length > 0) {
        doc.addPage();
        pageNum++;

        doc.setFillColor(...hexToRGB(COLORS.bg));
        doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

        // Section title
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...hexToRGB(COLORS.text));
        doc.text('AI Insights & Recommendations', MARGIN, MARGIN + 8);

        // Accent line
        doc.setDrawColor(...hexToRGB(COLORS.primary));
        doc.setLineWidth(0.5);
        doc.line(MARGIN, MARGIN + 12, PAGE_WIDTH - MARGIN, MARGIN + 12);

        // Gemini badge
        let iy = MARGIN + 22;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...hexToRGB(COLORS.primary));
        doc.text('Powered by Gemini AI', MARGIN, iy);
        iy += 8;

        // Insights text
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...hexToRGB(COLORS.text));

        const insightLines = doc.splitTextToSize(result.geminiInsights, CONTENT_WIDTH);
        for (const line of insightLines) {
            iy = ensureSpace(doc, iy, 5);
            if (iy <= MARGIN + 15) {
                doc.setFillColor(...hexToRGB(COLORS.bg));
                doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');
            }
            doc.text(line, MARGIN, iy);
            iy += 4.5;
        }

        drawFooter(doc, pageNum);
    }

    // Add page backgrounds and footers for all pages after page 1
    const totalPages = doc.getNumberOfPages();
    for (let p = 2; p <= totalPages; p++) {
        doc.setPage(p);
        drawFooter(doc, p);
    }

    // ── Save ──
    const safeName = (floorPlanName || 'floor-plan').replace(/[^a-zA-Z0-9-_]/g, '_');
    const timestamp = new Date().toISOString().slice(0, 10);
    doc.save(`${safeName}_accessibility_report_${timestamp}.pdf`);
}
